spring.application.name=backend
spring.config.import=optional:classpath:application-local.properties

# Conexiunea la baza de date
spring.datasource.url=jdbc:mysql://localhost:3306/agromanager_db?createDatabaseIfNotExist=true&serverTimezone=Europe/Bucharest
spring.datasource.username=root
spring.datasource.password=root

server.port=8081

app.demo-data.enabled=false

# Configurari Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

sentinel-hub.client-id=${SENTINEL_HUB_CLIENT_ID:}
sentinel-hub.client-secret=${SENTINEL_HUB_CLIENT_SECRET:}
